### ISSUE TITLE
Can't detect Camera2 Front Camera.

### ISSUE THREAD

**Issue by grantespo** [Ziggeo/Android-Client-SDK#13]
On API versions >= 21, I want to use Camera2 as the front camera. But the default still start as back camera

if(android.os.Build.VERSION.SDK_INT >= 21){
                    ziggeo.createVideo(Context, maxVideoDuration, CameraCharacteristics.LENS_FACING_FRONT, CameraHelper.Quality.HIGH, callback);
                }
                else{
                    ziggeo.createVideo(Context, maxVideoDuration, Camera.CameraInfo.CAMERA_FACING_FRONT, CameraHelper.Quality.HIGH, callback);

                }

**Comment by 3akat** [comment]
Hi @grantespo,
We have no support of camera2 api for now, please use `Camera.CameraInfo.CAMERA_FACING_FRONT` too
