### ISSUE TITLE
Error Existing from Video Player screen

### ISSUE THREAD

**Issue by jiahaoliuliu** [Ziggeo/Android-Client-SDK#2]
Hi:
I am using the full screen video feature to record the video. After the video has been correctly recorded, I press the stop button, select the cover and click on the play button. The problem is after the video is correctly played, there is not way for me to come back to the previous screen other than press the physical back button. If I press it, the screen shown is the recording screen, not the one which allows me to upload or play the current video, so there is not way after play a video to upload the video played.

Please, save the state of the screen before I play the video so when I come back, I can still decide if I should upload the video or record a new video.

Thanks.

**Comment by 3akat** [comment]
Hi @jiahaoliuliu,
Done, please check.
