### ISSUE TITLE
Crash using attachRecorder

### ISSUE THREAD

**Issue by gustafah** [Ziggeo/Android-Client-SDK#20]
Found an issue when I use attachRecorder, to use a Fragment on my layout to display the recorder.

When I tap record Icon, it immediately crashes. The issue is that the CacheFile comes as Null. Analysing the code. I found an issue, and was going to Fork the project and fix it, when I realized it's just a Demo Project that is on Github.

The issue I found was on lines:

> 559 - Fragment fragment = VideoRecorderFragment.getInstance(getCacheFolder(), this.maxRecordingDuration);
> 560 - fragment.setArguments(this.recorderBundleInitialisation());

On file **Ziggeo.class**.

Inside **VideoRecorderFragment.getInstance**, you already use **setArguments**,  with ARG_PATH. But when you do this second **setArguments** on line 560, ARG_PATH gets lost, which causes a crash when I try to record it.

**Comment by 3akat** [comment]
Hi @gustafah,
Thanks for reporting, will take a look shortly.

**Comment by 3akat** [comment]
@gustafah 
Please, take a look at the `0.73.9` version

**Comment by gustafah** [comment]
Oh, nice. Will have a look. is the version live already?

**Comment by gustafah** [comment]
I changed the version on my Gradle, 0.73.9, cleaned, rebuilt and it still presents the same issue.

**Comment by 3akat** [comment]
Can you please tell the steps? Maybe I have missed something

**Comment by gustafah** [comment]
This is what I'm doing to initialize:

> Ziggeo ziggeo = new Ziggeo(appToken, this);
> ziggeo.setMaxRecordingDuration(10 * 1000); //10 seconds
> ziggeo.setVideoRecordingProcessCallback(recordingCallback);
> ziggeo.setNetworkRequestsCallback(networkCallback);
> ziggeo.setPreferredCameraFacing(CameraView.FACING_FRONT);
> ziggeo.setPreferredQuality(CameraView.QUALITY_HIGH);
> ziggeo.setExtraArgsForRecorder(extraArgs);
> ziggeo.setSendImmediately(false);
> ziggeo.setCameraSwitchDisabled(true);
> ziggeo.attachRecorder(getSupportFragmentManager(), frameLayout.getId());

When I look at the code, for the **ziggeo.attachRecorder**, it still has the same lines I described on the original comment, on **defaultRecorderInitialisation()**.

**Comment by gustafah** [comment]
> Fragment fragment = VideoRecorderFragment.getInstance(getCacheFolder(), this.maxRecordingDuration);
> fragment.setArguments(this.recorderBundleInitialisation());

on **VideoRecorderFragment.getInstance()**, you already use **setArguments()**. then, you set it again on the snippet above.

**Comment by gustafah** [comment]
Now It's perfect! Issue solved ;) Thx a lot for the awesome tool.
