### ISSUE TITLE
Activity won't finish

### ISSUE THREAD

**Issue by AllinGaming** [Ziggeo/Android-Client-SDK#21]
When i record a video with attachrecorder and click the stop button, then select the cover shot the activity doesn't finish, i just get a white screen and when the upload finishes i get the recorder back. How can i make it finish like when i click the check button?

**Comment by 3akat** [comment]
Hi @AllinGaming 
Regarding the first question - right now there is no way to do this, we will think about how to improve business logic for such case.
Regarding the second - we're preparing the list of arg, once it will be finished I'll add it to the readme and will let you know.

**Comment by 3akat** [comment]
Hi @AllinGaming,
Regarding the first issue - please, take a look at the version `v.0.73.11`. It should behave as requested.

**Comment by 3akat** [comment]
@AllinGaming 
Actually, we already have such list, please take a look here
https://ziggeo.com/docs/sdks/javascript/browser-integration/parameters#javascript-revision=stable&javascript-version=v2
You need **Video management parameters** section.

**Comment by 3akat** [comment]
@AllinGaming closing the issue. Please, let us know if you need any additional help.
