### ISSUE TITLE
Unable to playback video using video token

### ISSUE THREAD

**Issue by abhisekm** [Ziggeo/Android-Client-SDK#22]
` String videoToPlay1 = "-- Video Token here --"; `
` ziggeo.startPlayer(videoToPlay1);`

I am getting Player Error with the following error

`2019-02-27 17:17:57.002 15639-15639/com.ziggeo.androidsdk.demo D/ZiggeoPlayerActivity: Player. Error`
`    java.io.IOException: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 1182 path $.streams[0].push_services_success`
`        at com.ziggeo.androidsdk.net.callbacks.BaseRxRequestCallback.onResponse(BaseRxRequestCallback.java:52)`
`        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)`
`        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)`
`        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)`
`        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)`
`        at java.lang.Thread.run(Thread.java:764)`

**Comment by Bane-D** [comment]
Hi Abhisek,

Looking at the error it seems that it might be connected to the JSON that was sent back from our server.

Can you please send us an email to support@ziggeo.com with the application token and video token you are using? That would allow us to check it out and see what might have happened.

Regards,
Bane

**Comment by 3akat** [comment]
Hi Abhisek,
Please take a look at the newest version.

**Comment by abhisekm** [comment]
Thank you for the fix, it is working now.
