### ISSUE TITLE
Changing Video quality or Camera facing has no effect

### ISSUE THREAD

**Issue by abhisekm** [Ziggeo/Android-Client-SDK#23]
`  Ziggeo ziggeo = new Ziggeo(APP_TOKEN, this);`
`  RecorderConfig config = new RecorderConfig.Builder()`
`                .callback(prepareCallback())`
`                .quality(CameraView.QUALITY_LOW)`
`                .facing(CameraView.FACING_FRONT)`
`                .sendImmediately(false)`
`                .enableCoverShot(false)`
`                .maxDuration(20000)`
`                .build();`

` ziggeo.configureRecorder(config);`
` ziggeo.startCameraRecorder();`

I am using the above code, but quality and camera facing is not changing. 

In file `com.ziggeo.androidsdk.ui.fragments.BaseVideoRecorderFragment`, `init()` function, `getArguments()` is always returning null when using `ziggeo.startCameraRecorder()` hence its skipping the init of variables from RecorderConfig and using default values. Can you see into this problem.

Thank you.

**Comment by abhisekm** [comment]
As a temporary fix, I am creating a custom CameraActivity class to add argument so that the init logic is not skipped.

[https://gist.github.com/abhisekm/0f922b227f274a1bee851da7eaa32606](url)

**Comment by 3akat** [comment]
Hi @abhisekm, working on it.

**Comment by 3akat** [comment]
Fixed, please take a look at the latest version.

**Comment by abhisekm** [comment]
Thank you for the quick fix.
