### ISSUE TITLE
Save the video while recording for every 5 min and capture the images also.

### ISSUE THREAD

**Issue by sriramsurya** [Ziggeo/Android-Client-SDK#24]
Save the video while recording for every 5 min and capture the images also.

**Comment by 3akat** [comment]
Can you please describe the feature you need to have? Do you need the video to be divided into 5min parts and have a snapshot for each? Or you just need a frame from every 5 mins of the video?
Do you need all the parts uploaded as separate things, or maybe process them locally?
Would be cool to hear as many details as possible :)

**Comment by 3akat** [comment]
closing it, since there is no details regarding the request.
