### ISSUE TITLE
NullPointer uploading the video

### ISSUE THREAD

**Issue by jiahaoliuliu** [Ziggeo/Android-Client-SDK#3]
Hi:
I got a null pointer exception after record the video and trying to upload it:

```
11-05 11:30:03.728 E/AndroidRuntime(32096): FATAL EXCEPTION: Thread-7369
11-05 11:30:03.728 E/AndroidRuntime(32096): Process: com.jiahaoliuliu.simpleziggeointegration, PID: 32096
11-05 11:30:03.728 E/AndroidRuntime(32096): java.lang.NullPointerException
11-05 11:30:03.728 E/AndroidRuntime(32096): 	at com.ziggeo.androidsdk.ui.fragments.VideoRecorderFragment$1.run(VideoRecorderFragment.java:189)
11-05 11:30:03.728 E/AndroidRuntime(32096): 	at java.lang.Thread.run(Thread.java:841)
```

I am not doing anything special. The source code could be found here:
https://github.com/jiahaoliuliu/SimpleZiggeoIntegration

**Comment by jiahaoliuliu** [comment]
Update: This happens on the full screen video recorder but not with Embedded video recorder

**Comment by jiahaoliuliu** [comment]
Update2: Now it is happening on embedded video recorder too...

**Comment by 3akat** [comment]
@jiahaoliuliu 
Hi,
I couldn't reproduce, but attempted to fix, please check now.
Thanks

**Comment by jiahaoliuliu** [comment]
@3akat Ok. I will try it tomorrow.
