### ISSUE TITLE
Use on Android 11 without external file storage access

### ISSUE THREAD

**Issue by Fi-Taka** [Ziggeo/Android-Client-SDK#40]
Is it possible to use this SDK on Android 11, where access for READ_EXTERNAL_STORAGE is not permitted? I have not been able to get things working thus far on `v2.5.7`:

* Using `ziggeo.startCameraRecorder()` gets stuck repeatedly flashing the "Camera, Audio, and Write storage access is needed to make recording" message (once you give camera and audio permissions) - probably because the write storage permission request will immediately fail at the OS-level.
* Using `ziggeo.startFileSelector()` results in an empty page with the "Read storage access is needed to select a file" message, probably for the same reason as the above bullet point.
* Using `ziggeo.videos().create()` is simply creating an "empty" video file in the dashboard. With Android 11, we must now access media through the `contentResolver`, which results in a URI with the scheme `content://`. Even if I then copy this into a `File` in internal app storage, the Ziggeo SDK seems to fail to find the contents to upload (although again, an "empty" video is created on the server). I'm not entirely sure why this is - perhaps the SDK can't access the app's internal storage. This also fails if I attempt to pass the `content://` URI path or copied internal file path into the `argsMap` for the `file` key-value pair.

Is there anything more I can do here? Would it be possible to have `ziggeo.videos().create` accept `java.io.InputStream`?

**Comment by smihir94** [comment]
@Fi-Taka are you able to find any workaround for this?

**Comment by smihir94** [comment]
@Fi-Taka 
implementation 'com.ziggeo:android-sdk:2.6.20' fixed this issue for me.
