### ISSUE TITLE
Doesn't work with Android 13 - External Storage Permission always Denied

### ISSUE THREAD

**Issue by smihir94** [Ziggeo/Android-Client-SDK#41]
Since Android 13 these 2 permissions are always denied

_android.permission.READ_EXTERNAL_STORAGE
android.permission.WRITE_EXTERNAL_STORAGE_

SDK is opening new Blank Activity with storage access error message on bottom.

**Update Ziggeo Android SDK to work with Android 13 - Tiramisu Devices.**

Can you please add support for this? Thanks a lot in advance.

**Comment by smihir94** [comment]
Hello, Any progress on this task?

**Comment by Bane-D** [comment]
Hi there,

One of our colleagues is looking into this to see what might be happening and if we can add this into current sprint or if it might need to go to next one. We will need to follow up with you as we learn more.

**Comment by smihir94** [comment]
Sure, Thanks

**Comment by smihir94** [comment]
Hi @Bane-D Do you have any updates on this issue?

**Comment by 3akat** [comment]
Hey @smihir94!
Please take a look at the version `2.6.15` - should be fixed there

**Comment by smihir94** [comment]
@3akat 
I tried and it is still giving me blank screen with an error message on bottom. can you take a look please? Attached screenshot below.

![Screenshot_20230728_155131_MyRegistry](https://github.com/Ziggeo/android-sdk-demo/assets/26103731/413beb9c-c167-4a47-92a9-15cd3c228eae)

**Comment by smihir94** [comment]
@3akat  Did you get a chance to look into the screenshot I have posted?

**Comment by smihir94** [comment]
Hi @3akat or @Bane-D can you please take a look at the screenshot I have attached? This feature is on priority and it's stopping us from releasing the next version for our App.

**Comment by objectorientedperson** [comment]
Facing the issue, any progress on this? @3akat

**Comment by aliceLit** [comment]
try to add androidx.work:work-rintime-ktx.2.7.1  // crash fro Android 12+, 
Note: read, write permission should be updated fro API level 33

**Comment by smihir94** [comment]
> try to add androidx.work:work-rintime-ktx.2.7.1 // crash fro Android 12+, Note: read, write permission should be updated fro API level 33

I tried with the version you have provided. I'm still getting the black screen with the error strip on bottom. (ss attached.) can you please take a look?

ss : https://imgur.com/fnNkjRK

**Comment by 3akat** [comment]
Please take a look at the version 2.6.20

**Comment by objectorientedperson** [comment]
@3akat unfortunately. Besides in Android 14 it directly crashes while asking for permissions.

**Comment by 3akat** [comment]
@objectorientedperson can you please double check you've update the version?
I spent some time today trying to reproduce the issue with local and remote dependency - works fine.
If you still face it, can you please specify exact steps on our demo app? 
Would be helpful!

**Comment by smihir94** [comment]
@3akat I have checked with updating version 2.6.2 and also with the latest version 2.6.5.
The result is still same on Android 13 devices. Can you take a look? 
In my App, targetSdkVersion = 33 and Test Device OS is Android 13

**Comment by 3akat** [comment]
@smihir94 Please try this version 
implementation('com.ziggeo:android-sdk:2.6.20') {
        transitive = true
 }

**Comment by smihir94** [comment]
Thank you. @3akat @aliceLit @Bane-D 
_implementation 'com.ziggeo:android-sdk:2.6.20'_ 
Fixed the issue on Android 13+ devices.
