### ISSUE TITLE
jitpack subscription fail

### ISSUE THREAD

**Issue by aliceLit** [Ziggeo/Android-Client-SDK#42]
Subscription is not active right now
Requested subscription: github.com/ziggeojitpackservice. 
Your subscriptions are listed in https://jitpack.io/w/user
Please contact Support or repository admins if you need assistance.

**Comment by LukasVykuka** [comment]
This issue reappeared again.

**Comment by Bane-D** [comment]
Hey Lukas,

Thank you for letting us know. It should be working fine, we are looking into why that is showing to you and what might be needed.

**Comment by Bane-D** [comment]
Hi Lukas,

I had reached out to Jit Service team and they were very helpful about the same and it seems that there was an issue on our part causing this, which should not cause any trouble for you now.

Please do try again to see if it works for you and do let us know how it goes.

**Comment by LukasVykuka** [comment]
It works, thank you.

**Comment by Bane-D** [comment]
Happy to hear that Lukas, thank you for reporting it :)
