### ISSUE TITLE
Application is not responding after playing preview on API 27+

### ISSUE THREAD

**Issue by petrssk** [Ziggeo/Android-Client-SDK#43]
Hello

I just added the Android SDK to the app and tried the camera recorder. It successfully launches the recording activity so I'm able to start recording. However, after stopping recording and trying to play the video I recorded, the application is not responding and nothing happens. I tried it on multiple Android versions and was able to reproduce it on API 27+, on lower APIs it works fine and opens the player with recorded video.

From the logs:
```
com.ziggeo.androidsdk.ui.activities.CameraRecorderActivity (server) is not responding. Waited 5000ms for FocusEvent(hasFocus=false))
```

I tried dependency from docs:
```
com.github.ZiggeoJitpackService:Android-SDK:2.6.5
```
and even some I found in some github issue:
```
com.ziggeo:android-sdk:2.6.20
```

Usage:
```
val ziggeo = Ziggeo(APP_TOKEN, requireContext())
ziggeo.startCameraRecorder()
```

Can you please check this issue?

**Comment by Bane-D** [comment]
Hi Petr,

One of my colleagues will look into it and reach out to you with more details. In the meantime can you please let us know if you have tried this on actual device or on virtual one?

PS: I noticed that you have also written to us on forum, so I went ahead and removed that post to avoid duplicates as this would likely be better place for you (and anyone else with same issue) to track the development on this.

**Comment by petrssk** [comment]
I tried only virtual devices but now when I try the actual device playing the preview works fine. However, I was able to test it only on two phones (API 30 and 34). 

Is this some known issue? Because I don't really understand why it works on virtual devices with API <27. Initially, I suspected an old version of exoplayer but I was wrong I guess.

**Comment by Bane-D** [comment]
I suspected the same Petr so thank you for the input, I believe that there is a typo in your last reply and that you actually only had the issue with virtual and that actual devices worked properly.

Depending on the many different things virtual phones or cameras might not work as expected. We had and still have the same requirement and generally the best results come from testing on actual devices.

You can read more specific info about it here:
https://www.browserstack.com/android-emulators
https://www.browserstack.com/emulators-simulators

Generally the virtual or simulated devices are great for many different tests, for video this was always lacking.

**Comment by petrssk** [comment]
Yeah sorry about the typo, the only issue I had was with virtual devices.

**Comment by Bane-D** [comment]
All good and thank you Petr for confirming so that we know.

I will leave it to my colleague to update you based on his findings if we can do anything about that or not.

Just as a potential info that will likely help - can you tell us what emulator did you use for testing on the same?
