### ISSUE TITLE
Video upload progress is return wrong values.

### ISSUE THREAD

**Issue by smihir94** [Ziggeo/Android-Client-SDK#44]
After recording the video, while uploading I believe we're getting the wrong values in the below callback function.

void uploadProgress(@NonNull String videoToken, @NonNull File file, long uploaded, long total);

uploaded bytes have greater value compared with total bytes. Attached is SS for reference. 
Can someone from the team help me with this?

_using implementation 'com.ziggeo:android-sdk:2.6.20'_

![image](https://github.com/Ziggeo/android-sdk-demo/assets/26103731/0c02bd13-117c-4fd7-af67-615206893c1d)

**Comment by Bane-D** [comment]
Hey Mihir,

That does look off to me as well. At first (before seeing screenshot) I thought the numbers were not too much apart which would be possible when the uploaded bytes are not recognized / corrupted and they get re-uploaded again, however seeing how much the difference is it would be best looked into by my colleague.

Assigning to him so he can get back to you on this.

In the mean time can you please let us know if this happens every time and if you are using same file if the values are same or different every time?

**Comment by smihir94** [comment]
Thank you @Bane-D 

Yes, this happens every time after recording the video, when the video is being uploaded to the server. So yeah the values and files are different every time.

**Comment by 3akat** [comment]
Hi @smihir94  Please try 2.6.21 version

**Comment by smihir94** [comment]
Thank you @3akat. It's working fine now.
