### ISSUE TITLE
Recording video error on Nexus 7

### ISSUE THREAD

**Issue by wandersage** [Ziggeo/Android-Client-SDK#7]
Hi. I tested my application with Ziggeo SDK and have crashes on Nexus 7 device. 
[Crashlytics](http://crashes.to/s/5e2474492be) issue. Could you help me?

**Comment by 3akat** [comment]
Hi Anton, 
Will check this on weekends.

**Comment by 3akat** [comment]
@wandersage fixed in 0.42.0 version
