### ISSUE TITLE
Laucher Icon Collision

### ISSUE THREAD

**Issue by superibk** [Ziggeo/Android-Client-SDK#8]
Am using the Android SDk and got this error "ic_launcher.png: error: Duplicate file" and "ic_launcher.png: Original is here, The version qualifier may be implied". 
It appears that, there is ic_launcher.png in the library which collided with the default "ic_launcher.png". to work around this i had to either add the -v4 qualifier to  resource folders , move just ic_launcher.png to *dpi-v4 or rename it

**Comment by 3akat** [comment]
Hi @superibk,
Will fix it today.

**Comment by 3akat** [comment]
Hey @superibk 
I removed all laucher icons, please check.
